package defaults

// Code generated by tools/scripts/generate-defaults.mjs. DO NOT EDIT.

var generatedDefaults = generatedDefaultsSpec{
	State: generatedStateDefaults{
		ProductionDirName:    ".tutti",
		DevelopmentDirName:   ".tutti-dev",
		RunDirName:           "run",
		ListenerInfoFileName: "tuttid.listener.json",
	},
}
